Regression va Classification — Machine Learning’dagi eng asosiy ikki turdagi masala. Eng oson farqi:

🔵 Regression → natija son bo‘ladi
🟢 Classification → natija kategoriya/sinf bo‘ladi.
Regression modeli raqamli qiymatlarni bashorat qiladi. 
hayotiy misol uy maydonimiz 50m/kv bulsin yashovchi soni 4kishi kinlik foydalaniladigan elektr energiya 10 soat bulsa demakki 350kWh buladi.
Classification modeli obyektni malum bir kategoriyalarga buladi. Masalan, emailni spam yoki spam emasligini aniqlash:

Email
   ↓
Machine Learning
   ↓
Spam / Not Spam  Natija bulsa: Spam. Bu son emas, kategoriyadir.

In [2]:
import os, glob, shutil
import urllib.request as r


def data_download(dir_file, data_name = "college"):
  data_names = ["salaries", "exams", "college", "cars", "mall"]
  assert data_name in data_names, f"Mavjud bo'lgan dataset {data_names} dan birini kiriting"

  if data_name == "college": url = "https://drive.google.com/file/d/1vwfMpQ4ikAI91zn1bWxP_Iqz7DTFUA9F/view?usp=sharing"
  elif data_name == "salaries": url = "https://drive.google.com/file/d/1p-XtX29fgXT9CzBfpHm3t8r028gQPRhe/view?usp=sharing"
  elif data_name == "exams": url = "https://drive.google.com/file/d/1TYN_sRmauaDgNYgQ-0VSHVAJvLoxKx2R/view?usp=sharing"
  elif data_name == "cars": url = "https://drive.google.com/file/d/1Fi5IPdfEktnKyf3dyHmnh84a2jiXl33A/view?usp=sharing"
  elif data_name == "mall": url = "https://drive.google.com/file/d/1eGWJVRNmGjfaH0o3dczBbNe_-RrW0_Jm/view?usp=sharing"

  full_path = f"{dir_file}/{data_name}.zip"
  os.makedirs(dir_file, exist_ok = True)

  if os.path.isfile(f"{dir_file}/{data_name}.csv"): print("Data downloaded")
  else:
    print("Downloading data started...")

    file_id = url.split("/")[-2]

    # Initialize prefix to download
    prefix = "https://drive.google.com/uc?/export=download&id="

    # Download the checkpoint
    r.urlretrieve(f"{prefix + file_id}", f"{full_path}")
    shutil.unpack_archive(f"{full_path}", f"{dir_file}")
    os.remove(full_path)

    files = sorted(glob.glob(f"{dir_file}/*"), key = os.path.getctime)
    fname = os.path.basename(files[-1])
    os.rename(f"{dir_file}/{fname}", f"{dir_file}/{data_name}.csv")
    print(f"Data {dir_file} papkasiga {data_name} nomi bilan yuklab olindi.")

In [3]:
data_download(dir_file="datasetlar", data_name="exams")

Data downloaded

In [14]:
import pandas as pd

df = pd.read_csv("datasetlar/exams.csv")
df.head() # malumotni tekshirib kurish.

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df_exams = pd.read_csv("datasetlar/exams.csv")
df_exams.shape
# df_exams.info()

(1000, 8)

In [7]:
import pandas as pd
import numpy as np

df_uzbekistan_football = pd.read_csv("datasetlar/uzbekistan_football.csv")
df_uzbekistan_football.shape  # hajmini tekshirish

(10, 10)

In [8]:
df_exams.head() # df_exams mavjudligi tekshirib olamiz.

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer

In [22]:
print(df_exams.columns.tolist())

['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

In [35]:
X = df_exams.drop("math score", axis=1)
y = df_exams["math score"].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# kategorik ustunlar — reading/writing score bundan mustasno, chunki ular sonli (numeric)
cat_cols = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']
num_cols = [col for col in X.columns if col not in cat_cols]  # bu yerda ['reading score', 'writing score'] chiqadi

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
    ('num', StandardScaler(), num_cols)
])

X_train_transform = preprocessor.fit_transform(X_train)
X_test_transform = preprocessor.transform(X_test)

model_lr = LinearRegression()
model_lr.fit(X_train_transform, y_train)

LinearRegression()

In [37]:
acc_score = model_lr.score(X_test_transform, y_test)
print(f"Aniqlilik -> {(acc_score * 100):.2f}%")

Aniqlilik -> 88.04%

In [38]:
model_dt = DecisionTreeRegressor()
model_dt.fit(X_train_transform, y_train)

DecisionTreeRegressor()

In [39]:
acc_score = model_dt.score(X_test_transform, y_test) # acc score 0~1 * 100
print(f"Aniqlilik -> {(acc_score * 100):.2f}%")

Aniqlilik -> 69.69%

In [42]:

model_rf = RandomForestRegressor()
model_rf.fit(X_train_transform, y_train)

RandomForestRegressor()

In [43]:
acc_score = model_rf.score(X_test_transform, y_test) # acc score 0~1 * 100
print(f"Aniqlilik -> {(acc_score * 100):.2f}%")

Aniqlilik -> 85.16%

UZBEKISTAN_FOOTBALL Practice

In [44]:
df_uzbekistan_football.head()

,club,city,matches,wins,draws,losses,goals_scored,goals_conceded,points,average_age
0,Nasaf,Qarshi,26,18,5,3,52,20,59,25.3
1,Pakhtakor,Toshkent,26,17,6,3,49,22,57,26.5
2,Navbahor,Namangan,26,15,7,4,45,24,52,24.9
3,Neftchi,Farg'ona,26,13,8,5,41,27,47,25.7
4,AGMK,Olmaliq,26,14,6,6,43,29,48,26.1

In [48]:
df_uzbekistan_football = df_uzbekistan_football.rename(columns= {"Unnamed: 0": "city"})

X = df_uzbekistan_football.drop("points", axis=1)
y = df_uzbekistan_football["points"].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

cat_cols = ["club", "city"]
num_cols = [col for col in X.columns if col not in cat_cols]

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
    ('num', StandardScaler(), num_cols)
])

X_train_transform = preprocessor.fit_transform(X_train)
X_test_transform = preprocessor.transform(X_test)

model_lr = LinearRegression()
model_lr.fit(X_train_transform, y_train)

LinearRegression()

In [49]:
# math score va reading score — X ning featurelari bo'ladi, writing score esa Xdan chiqarilib, y bo'ladi.

X = df_exams.drop("writing score", axis=1)
y = df_exams["writing score"].copy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

cat_cols = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']
num_cols = [col for col in X.columns if col not in cat_cols]  # ['math score', 'reading score']

preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
    ('num', StandardScaler(), num_cols)
])

X_train_transform = preprocessor.fit_transform(X_train)
X_test_transform = preprocessor.transform(X_test)

model_lr_writing = LinearRegression()
model_lr_writing.fit(X_train_transform, y_train)

LinearRegression()